kind = "web"
previewPath = "/"
title = "ProHub"
version = "1.0.0"
id = "artifacts/prohub"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20627

[services.development]
run = "pnpm --filter @workspace/prohub run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/prohub", "run", "build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["pnpm", "--filter", "@workspace/prohub", "run", "start"]

[services.production.run.env]
PORT = "20627"
NODE_ENV = "production"

[services.env]
PORT = "20627"
